import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RootModal } from "../components/ui/modals/rootModal";
import { Header } from "@/components/layout/header";
import { StarIcon } from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
    >
      <body className="min-h-full flex flex-col p-4">
        <Header>
          <Link href="/" aria-label="Go to home">
            <StarIcon className="w-13 h-13  transition-transform duration-200 hover:rotate-[-15deg] cursor-pointer" aria-label="Logo"/>
          </Link>
          <h1>Star</h1> 
        </Header>
          
        <main className="flex flex-1 flex-col">
          {children}  
        </main>
        <footer>
          footer
        </footer>
         <RootModal/>
      </body>
    </html>
  );
}
